Test Scenario Kelompok 4
------------------------
Link list sheet uji coba:https://docs.google.com/spreadsheets/d/1weHAqknIz9r2k1jKYsd56J_lPUBkKmc-mKpGHXByhcg/edit?usp=sharing
Pembuatan test scenario, eksekusi test, dan perbaikan kode untuk test case yang fail pada api:

* Create Order
* Cancel Order
* Revise Order

[cols="1,2,2,3,3,2,2"]
.Test Scenario
|===
| Test Id | Test Case Name | Precondition | Test Data | Expected Result | Result | Actual Reslut

| TC01 |Membuat order baru dengan data consumer yang sudah terdaftar | 
- Sudah ada data restaurant yang tersimpan,

- Sudah ada data menu pada restaurant yang dipilih,

- Customer telah terdaftar,
| Create Restaurant :
{
  "consumerId": 9,
  "deliveryAddress": {
    "city": "bandung",
    "state": "indonesia",
    "street1": "ciwaruga",
    "street2": "polban",
    "zip": "40559"
  },
  "deliveryTime": "2024-04-04T16:16:00.125Z",
  "lineItems": [
    {
      "menuItemId": "001",
      "quantity": 1
    }
  ],
  "restaurantId": 2
}
} | Expected Result:
Order akan terbuat dan pemanggilan endpoint API akan mengembalikan response berupa orderId dari order yang baru terbuat


Response: 
{ "orderId": 1}
} | PASS | Actual Result:
Order akan terbuat dan pemanggilan endpoint API akan mengembalikan response berupa orderId dari order yang baru terbuat


Response:
{ "orderId": 1}


| TC02 | Membuat order baru dengan data consumer yang tidak terdaftar | 
- Sudah ada data restaurant yang tersimpan

- Sudah ada data menu pada restaurant yang dipilih 
| {
  "consumerId": 100,
  "deliveryAddress": {
    "city": "bandung",
    "state": "indonesia",
    "street1": "ciwaruga",
    "street2": "polban",
    "zip": "40559"
  },
  "deliveryTime": "2024-04-04T16:16:00.125Z",
  "lineItems": [
    {
      "menuItemId": "001",
      "quantity": 1
    }
  ],
  "restaurantId": 2
}| Expected Result:
Order akan gagal terbuat dan pemanggilan endpoint API akan mengembalikan response berupa error karena consumer tidak terdaftar


Response:
{ ""timestamp"": ""2024-04-05T09:07:55.338+0000"", ""status"": 500, ""error"": ""Internal Server Error"", ""message"": ""Consumer not found with id 100"", ""path"": ""/orders""}
} | FAIL | Actual Result:
Order berhasil terbuat dan pemanggilan endpoint API akan mengembalikan response berupa orderId dari order yang baru terbuat


Response: 
{ "orderId": 2}

| TC03 | Membuat order baru dengan data restaurant sudah terdaftar |
- Sudah ada data restaurant yang tersimpan

- Sudah ada data menu pada restaurant yang dipilih 

- Customer telah terdaftar  | 
{
  "consumerId": 100,
  "deliveryAddress": {
    "city": "bandung",
    "state": "indonesia",
    "street1": "ciwaruga",
    "street2": "polban",
    "zip": "40559"
  },
  "deliveryTime": "2024-04-04T16:16:00.125Z",
  "lineItems": [
    {
      "menuItemId": "001",
      "quantity": 1
    }
  ],
  "restaurantId": 2
}
} | Expected Result:
Order akan terbuat dan pemanggilan endpoint API akan mengembalikan response berupa orderId dari order yang baru terbuat


Response:
{
  "orderId": 3
}
} | PASS | Actual Result:
Order akan terbuat dan pemanggilan endpoint API akan mengembalikan response berupa orderId dari order yang baru terbuat


Response:
{
  "orderId": 3
}

| TC04 | Membuat order baru dengan data restaurant yang tidak terdaftar |   Customer telah terdaftar  | {
  "consumerId": 9,
  "deliveryAddress": {
    "city": "bandung",
    "state": "indonesia",
    "street1": "ciwaruga",
    "street2": "polban",
    "zip": "40559"
  },
  "deliveryTime": "2024-04-04T16:16:00.125Z",
  "lineItems": [
    {
      "menuItemId": "001",
      "quantity": 1
    }
  ],
  "restaurantId": 100
} | Expected Result:
Order akan gagal terbuat dan pemanggilan endpoint API akan mengembalikan response berupa error karena restaurant tidak terdaftar



Response:
{ "timestamp": "2024-04-05T09:07:55.338+0000", "status": 500, "error": "Internal Server Error", "message": "Restaurant not found with id 100", "path": "/orders"} | PASS | Actual Result:
Order akan gagal terbuat dan pemanggilan endpoint API akan mengembalikan response berupa error karena restaurant tidak terdaftar



Response:
{ "timestamp": "2024-04-05T09:07:55.338+0000", "status": 500, "error": "Internal Server Error", "message": "Restaurant not found with id 100", "path": "/orders"}

| TC05 | Membuat order dengan memilih menu yang tidak terdaftar | 
-Sudah ada data restaurant yang tersimpan 

-Sudah ada data menu pada restaurant yang dipilih

- Customer telah terdaftar  | {
  "consumerId": 9,
  "deliveryAddress": {
    "city": "bandung",
    "state": "indonesia",
    "street1": "ciwaruga",
    "street2": "polban",
    "zip": "40559"
  },
  "deliveryTime": "2024-04-04T16:16:00.125Z",
  "lineItems": [
    {
      "menuItemId": "100",
      "quantity": 1
    }
  ],
  "restaurantId": 02
}| Expected Result:
Order akan gagal terbuat dan pemanggilan endpoint API akan mengembalikan response berupa error karena menu yang dipilih tidak terdaftar


Response: 
{ "timestamp": "2024-04-05T09:03:38.056+0000", "status": 500, "error": "Internal Server Error", "message": "Invalid menu item id 100", "path": "/orders"}| PASS | Actual Result:
Order akan gagal terbuat dan pemanggilan endpoint API akan mengembalikan response berupa error karena menu yang dipilih tidak terdaftar


Response: 
{ "timestamp": "2024-04-05T09:03:38.056+0000", "status": 500, "error": "Internal Server Error", "message": "Invalid menu item id 100", "path": "/orders"}

| TC06 | Membuat order tanpa memilih menu | 
- Sudah ada data restaurant yang tersimpan 

- Sudah ada data menu pada restaurant yang dipilih 

- Customer telah terdaftar  | {
  "consumerId": 9,
  "deliveryAddress": {
    "city": "Bandung",
    "state": "Indonesia",
    "street1": "Ciwaruga",
    "street2": "Polban",
    "zip": "40559"
  },
  "deliveryTime": "2024-04-04T16:16:00.125Z",
  "lineItems": [ ],
  "restaurantId": 2
}
 | Order akan gagal terbuat dan pemanggilan endpoint API akan mengembalikan response berupa error karena tidak ada satupun menu yang terpilih | FAIL | Actual Result :
Order akan terbuat dan pemanggilan endpoint API akan mengembalikan response berupa orderId dari order yang baru terbuat


Response:
{
  "orderId": 4
}

| TC07 | Membuat order dengan memilih minimal satu menu | 
- Sudah ada data restaurant yang tersimpan

- Sudah ada data menu pada restaurant yang dipilih

- Customer telah terdaftar  | {
  "consumerId": 9,
  "deliveryAddress": {
    "city": "Bandung",
    "state": "Indonesia",
    "street1": "Ciwaruga",
    "street2": "Polban",
    "zip": "40559"
  },
  "deliveryTime": "2024-04-04T16:16:00.125Z",
  "lineItems": [
    {
      "menuItemId": "001", 
      "quantity": 2
    },
    {
      "menuItemId": "002",
      "quantity": 1
    }
  ],
  "restaurantId": 2
} | Order akan terbuat dan pemanggilan endpoint API akan mengembalikan response berupa orderId dari order yang baru terbuat | PASS | Actual Result :
Order akan terbuat dan pemanggilan endpoint API akan mengembalikan response berupa orderId dari order yang baru terbuat


Response:
{
  "orderId": 5
}

| TC08 | Membuat order dengan memilih menu dengan kuantitas minimal satu | 
- Sudah ada data restaurant yang tersimpan

- Sudah ada data menu pada restaurant yang dipilih 

- Customer telah terdaftar 
| {
  "consumerId": 9,
  "deliveryAddress": {
    "city": "Bandung",
    "state": "Indonesia",
    "street1": "Ciwaruga",
    "street2": "Polban",
    "zip": "40559"
  },
  "deliveryTime": "2024-04-04T16:16:00.125Z",
  "lineItems": [
    {
      "menuItemId": "001",
      "quantity": 5
    }
  ],
  "restaurantId": 2
}
| Order akan terbuat dan pemanggilan endpoint API akan mengembalikan response berupa orderId dari order yang baru terbuat
} | PASS | Actual Result :
Order akan terbuat dan pemanggilan endpoint API akan mengembalikan response berupa orderId dari order yang baru terbuat


Response:
{
  "orderId": 6
}

| TC09 | Membuat order dengan memilih menu dengan kuantitas kurang dari satu | Sudah ada data restaurant yang tersimpan, sudah ada data menu pada restaurant yang dipilih, customer telah terdaftar | {
  "consumerId": 9,
  "deliveryAddress": {
    "city": "Bandung",
    "state": "Indonesia",
    "street1": "Ciwaruga",
    "street2": "Polban",
    "zip": "40559"
  },
  "deliveryTime": "2024-04-04T16:16:00.125Z",
  "lineItems": [
    {
      "menuItemId": "001",
      "quantity": 0
    }
  ],
  "restaurantId": 2
}
 | Order akan gagal terbuat dan pemanggilan endpoint API akan mengembalikan response berupa error karena quantity kurang dari satu | FAIL | Actual Result :
Order akan terbuat dan pemanggilan endpoint API akan mengembalikan response berupa orderId dari order yang baru terbuat

Response:
{
  "orderId": 7
}

| TC10 | Mengubah order dengan mengganti kuantitas dengan nilai minimal satu | Sudah ada Order yang tersimpan | {
  "revisedOrderLineItems": [
    {
      "menuItemId": "001",
      "quantity": 3
    }
  ]
}| Kuantitas dari sebuah menu akan berubah sesuai kuantitas baru yang ditentukan dan pemanggilan endpoint API akan mengembalikan response berupa perubahan yang menampilkan orderId, state, dan orderTotal



Response:
{
    "orderId": 1,
    "state": "APPROVAL_PENDING",
    "orderTotal": "12.00"
} | PASS | Actual Result:
Kuantitas dari sebuah menu akan berubah sesuai kuantitas baru yang ditentukan dan pemanggilan endpoint API akan mengembalikan response berupa perubahan yang menampilkan orderId, state, dan orderTotal


Response:
{
    "orderId": 1,
    "state": "APPROVAL_PENDING",
    "orderTotal": "12.00"
}


| TC11 | Mengubah order dengan mengganti dengan kuantitas kurang dari satu | Sudah ada Order yang tersimpan | {
  "revisedOrderLineItems": [
    {
      "menuItemId": "001",
      "quantity": -4
    }
  ]
}| Kuantitas dari sebuah menu tidak akan berubah, pemanggilan endpoint API akan mengembalikan response berupa error karena kuantitas yang ditentukan kurang dari satu. | FAIL | Actual Result:
Kuantitas dari sebuah menu berubah sesuai kuantitas baru yang ditentukan dimana total harga disini bisa berupa nol dan negatif, dan pemanggilan endpoint API akan mengembalikan response berupa perubahan yang menampilkan orderId, state, dan orderTotal. 


Response:
{
  "orderId": 1,
  "state": "APPROVED",
  "orderTotal": "-28000.00"
}

| TC12 | Melakukan Pembatan Order | Sudah ada Order yang tersimpan | {
  "consumerId": 9,
  "deliveryAddress": {
    "city": "Bandung",
    "state": "Indonesia",
    "street1": "Ciwaruga",
    "street2": "Polban",
    "zip": "40559"
  },
  "deliveryTime": "2024-04-04T16:16:00.125Z",
  "lineItems": [
    {
      "menuItemId": "001",
      "quantity": 0
    }
  ],
  "restaurantId": 2
} | Order akan ter-cancel dan pemanggilan endpoint API akan mengembalikan response berupa perubahan yang menampilkan orderId, state, dan orderTotal


Response : {
    "orderId": 2,
    "state": "APPROVED",
    "orderTotal": "12.00"
} | PASS | Actual Result:
Order akan ter-cancel dan pemanggilan endpoint API akan mengembalikan response berupa perubahan yang menampilkan orderId, state, dan orderTotal. 


Response:
{
  "orderId": 2,
  "state": "APPROVED",
  "orderTotal": "12.00"
}

|===


Perubahan Kode
~~~~~~~~~~~~~~~

. Test case TC2
+
    * Bug/Masalah: 
    - Order dapat dilakukan walaupun dengan consumerId yang tidak ada pada sistem.
    * Perubahan yang dilakukan
    - Menambahkan kode untuk pengecekan consumerId ke consumerRepository terlebih dahulu sebelum pembuatan order dilakukan.
    - Menambahkan class Exception untuk menghandle ketika consumerId yang dicantumkan pada saat pembuatan order dilakukan tidak terdaftar pada sistem.
    * Kode setelah perubahan
    
        - Penambahan pengecekan consumerRepository pada class OrderService
+        
[source,java]
----
  public OrderService(SagaInstanceFactory sagaInstanceFactory,
                      OrderRepository orderRepository,
                      DomainEventPublisher eventPublisher,
                      RestaurantRepository restaurantRepository,
                      ConsumerRepository consumerRepository,
                      CreateOrderSaga createOrderSaga,
                      CancelOrderSaga cancelOrderSaga,
                      ReviseOrderSaga reviseOrderSaga,
                      OrderDomainEventPublisher orderAggregateEventPublisher,
                      Optional<MeterRegistry> meterRegistry) {

    this.sagaInstanceFactory = sagaInstanceFactory;
    this.orderRepository = orderRepository;
    this.restaurantRepository = restaurantRepository;
    this.consumerRepository = consumerRepository;
    this.createOrderSaga = createOrderSaga;
    this.cancelOrderSaga = cancelOrderSaga;
    this.reviseOrderSaga = reviseOrderSaga;
    this.orderAggregateEventPublisher = orderAggregateEventPublisher;
    this.meterRegistry = meterRegistry;
  }

  @Transactional
  public Order createOrder(long consumerId, long restaurantId, DeliveryInformation deliveryInformation,
                           List<MenuItemIdAndQuantity> lineItems) {
    Restaurant restaurant = restaurantRepository.findById(restaurantId)
            .orElseThrow(() -> new RestaurantNotFoundException(restaurantId));

    Consumer consumer = consumerRepository.findById(consumerId)
            .orElseThrow(() -> new ConsumerNotFoundException(consumerId));

    List<OrderLineItem> orderLineItems = makeOrderLineItems(lineItems, restaurant);

    ResultWithDomainEvents<Order, OrderDomainEvent> orderAndEvents =
            Order.createOrder(consumerId, restaurant, deliveryInformation, orderLineItems);

    Order order = orderAndEvents.result;
    orderRepository.save(order);

    orderAggregateEventPublisher.publish(order, orderAndEvents.events);

    OrderDetails orderDetails = new OrderDetails(consumerId, restaurantId, orderLineItems, order.getOrderTotal());

    CreateOrderSagaState data = new CreateOrderSagaState(order.getId(), orderDetails);
    sagaInstanceFactory.create(createOrderSaga, data);

    meterRegistry.ifPresent(mr -> mr.counter("placed_orders").increment());

    return order;
  }
----

        - Pembuatan class ConsumerNotFoundException
+
[source,java]
----
package net.chrisrichardson.ftgo.orderservice.domain;

public class ConsumerNotFoundException extends RuntimeException {
    public ConsumerNotFoundException(long consumerId) {
        super("Consumer not found with id " + consumerId);
    }
}

----

. Test case TC6
+
    * Bug/Masalah
    - Order dapat dilakukan walaupun tanpa memilih satupun menu.
    * Perubahan yang dilakukan
    - Menambahkan kode untuk pengecekan apakah lineItems kosong atau tidak sebelum melakukan pembuatan order.
    - Menambahkan class Exception untuk menghandle ketika lineItems (menu yang dipilih) kosong.
    * Kode setelah perubahan
    
        - Penambahan pengecekan isi dari lineItems pada class OrderService
+
[source,java]
----
  @Transactional
  public Order createOrder(long consumerId, long restaurantId, DeliveryInformation deliveryInformation,
                           List<MenuItemIdAndQuantity> lineItems) {
    Restaurant restaurant = restaurantRepository.findById(restaurantId)
            .orElseThrow(() -> new RestaurantNotFoundException(restaurantId));

    if (lineItems.isEmpty()) {
        throw new NoOrderItemsException();
    }

    List<OrderLineItem> orderLineItems = makeOrderLineItems(lineItems, restaurant);

    ResultWithDomainEvents<Order, OrderDomainEvent> orderAndEvents =
            Order.createOrder(consumerId, restaurant, deliveryInformation, orderLineItems);

    Order order = orderAndEvents.result;
    orderRepository.save(order);

    orderAggregateEventPublisher.publish(order, orderAndEvents.events);

    OrderDetails orderDetails = new OrderDetails(consumerId, restaurantId, orderLineItems, order.getOrderTotal());

    CreateOrderSagaState data = new CreateOrderSagaState(order.getId(), orderDetails);
    sagaInstanceFactory.create(createOrderSaga, data);

    meterRegistry.ifPresent(mr -> mr.counter("placed_orders").increment());

    return order;
  }
----
        - Pembuatan class NoOrderItemsException
+
[source,java]
----
package net.chrisrichardson.ftgo.orderservice.domain;

public class NoOrderItemsException extends RuntimeException {
    public NoOrderItemsException() {
        super("Order must have at least one item");
    }
}
----
. Test case TC9
+
    * Bug/Masalah
    - Order tetap dapat dibuat walaupun ada kuantitas pada meunu yang kurang dari 1.
    * Perubahan yang dilakukan
    - Menambahkan kode untuk melakukan pengecekan terlebih dahulu pada kuantitas tiap menu yang diorder agar tidak kurang dari 1.
    - Menambahkan class Exception untuk menghandle ketika ada menu yang kuantitasnya kurang dari 1 pada saat pembuatan order dilakukan.
    * Kode setelah perubahan
    
        - Penambahan pengecekan quantity pada lineItems pada class OrderService
+
[source,java]
----
private List<OrderLineItem> makeOrderLineItems(List<MenuItemIdAndQuantity> lineItems, Restaurant restaurant) {
    return lineItems.stream().map(li -> {
        if (li.getQuantity() <= 0) {
            throw new InvalidOrderQuantityException(li.getMenuItemId(), li.getQuantity());
        }
        MenuItem om = restaurant.findMenuItem(li.getMenuItemId()).orElseThrow(() -> new InvalidMenuItemIdException(li.getMenuItemId()));
        return new OrderLineItem(li.getMenuItemId(), om.getName(), om.getPrice(), li.getQuantity());
    }).collect(toList());
}

----
        - Pembuatan class InvalidOrderQuantityException
+
[source,java]
----
public class InvalidOrderQuantityException extends RuntimeException {
    private String menuItemId; 
    private int quantity;

    public InvalidOrderQuantityException(String menuItemId, int quantity) {
        super("Invalid quantity (" + quantity + ") for menu item: " + menuItemId);
        this.menuItemId = menuItemId;
        this.quantity = quantity;
    }

}
----

. Test case TC11
+
    * Bug/Masalah
    - Perubahan/Revise order dengan perubahan kuantitas pada menu menjadi kurang dari 1 dapat dilakukan.
    * Perubahan yang dilakukan
    - Menambahkan kode untuk pengecekan perubahan kuantitas pada tiap menu supaya harus lebih dari sama dengan 1.
    - Menambahkan class Exception untuk menghandle ketika ada perubahan kuantitas pada menu yang kurang dari 1.
    * Kode setelah perubahan
    
        - Penambahan pengecekan quantity baru pada setiap perubahan di LineItemQuantityChange pada class Order
+
[source,java]
----
public ResultWithDomainEvents<LineItemQuantityChange, OrderDomainEvent> revise(OrderRevision orderRevision) {
    switch (state) {

      case APPROVED:
        LineItemQuantityChange change = orderLineItems.lineItemQuantityChange(orderRevision);

        List<LineItemQuantityChange> changes = revision.getChanges();

        for (LineItemQuantityChange change : changes) {
            if (change.getNewQuantity() <= 0) {
                throw new InvalidRevisedOrderQuantityException(change.getMenuItemId(), change.getNewQuantity());
            }
        }

        if (change.newOrderTotal.isGreaterThanOrEqual(orderMinimum)) {
          throw new OrderMinimumNotMetException();
        }
        this.state = REVISION_PENDING;
        return new ResultWithDomainEvents<>(change, singletonList(new OrderRevisionProposed(orderRevision, change.currentOrderTotal, change.newOrderTotal)));

      default:
        throw new UnsupportedStateTransitionException(state);
    }
  }
----

        - Pembuatan class InvalidRevisedOrderQuantityException
+
[source,java]
----
public class InvalidRevisedOrderQuantityException extends RuntimeException {
    private String menuItemId; 
    private int quantity;

    public InvalidRevisedOrderQuantityException(String menuItemId, int quantity) {
        super("Invalid revised quantity (" + quantity + ") for menu item: " + menuItemId);
        this.menuItemId = menuItemId;
        this.quantity = quantity;
    }
}
----
